# Generated by Django 2.2.3 on 2019-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='noavatar.jpg', null=True, upload_to='profile/'),
        ),
    ]
